// ...existing code...
const userSchema = new mongoose.Schema({
  // ...existing code...
  login_name: { type: String, required: true, unique: true },
  // ...existing code...
});
// ...existing code...

